[package]
name = "wgpu-game-of-life"
version = "0.1.0"
edition = "2021"
description = "Wgpu game of life"
license = "MIT"
repository = "https://github.com/fornwall/wgpu-game-of-life"
keywords = ["advent-of-code"]
categories = ["graphics"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
bytemuck = { version = "*", features = ["derive"] }
env_logger = "*"
log = "*"
instant = { version = "*", features = ["wasm-bindgen"] }
pollster = "*"
rand = "*"
rand_chacha = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu", branch = "trunk" }
winit = { git = "https://github.com/rust-windowing/winit/", branch = "master", features = ["android-native-activity"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "*"
console_log = "*"
getrandom = { version = "*", features = ["js"] }
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
web-sys = { version = "*", features = ["Document", "Element", "Window"] }
js-sys = "*"

[package.metadata.bundle]
name = "Game of Life"
identifier = "net.fornwall.wgpugameoflife"
version = "0.1.0"
resources = ["assets", "images/**/*.png"]
copyright = "Copyright (c) Fredrik Fornwall 2023. All rights reserved."
category = "Developer Tool"
short_description = "An example wgpu application."
long_description = """
An example wgpu application running game of life.
Se https://github.com/fornwall/wgpu-game-of-life.
"""

[package.metadata.android]
package = "net.fornwall.wgpugameoflife"
build_targets = ["aarch64-linux-android", "x86_64-linux-android"]
apk_name = "wgpu-game-of-life"
fullscreen = true
launch_mode = "singleInstance"
strip = "strip"

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 33

[package.metadata.android.application]
label = "Game of Life"
