[package]
name = "wgpu-game-of-life"
version = "0.1.0"
edition = "2021"
description = "Wgpu game of life"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "*", features = ["derive"] }
env_logger = "*"
log = "*"
pollster = "*"
rand = "*"
wgpu = "*"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "*"
console_log = "*"
wgpu = { version = "*" }
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
web-sys = { version = "*", features = ["Document", "Element", "Window"] }
