name: CI

on:
  push:
    branches:
      - '**'

jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - run: make

  deploy-site:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Install wasm-opt
      run: brew update && brew install binaryen
    - run: cargo install wasm-bindgen-cli
    - run: make WASM_RELEASE=1 generate-wasm
    - name: Publish
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_PAGES_EDIT_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: wgpu-game-of-life-fornwall-net
        directory: site
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
