name: CI

on:
  push:
    branches:
      - '**'

jobs:
  check-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
    - run: make

  generate-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
    - run: make generate-wasm
    - run: test -f site/generated/wgpu_game_of_life_bg.wasm
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Install wasm-opt
      run: brew update && brew install binaryen
    - run: rm site/generated/wgpu_game_of_life_bg.wasm
    - run: make WASM_RELEASE=1 generate-wasm
    - run: test -f site/generated/wgpu_game_of_life_bg.wasm

  deploy-site:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Permissions necessary for ${{ secrets.GITHUB_TOKEN }}
    # to allow cloudflare/pages-action to create deployment:
    # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Homebrew/actions/setup-homebrew@master
    - name: Install wasm-opt
      run: brew update && brew install binaryen
    - uses: jetli/wasm-bindgen-action@v0.2.0
    - run: make WASM_RELEASE=1 generate-wasm
    - run: npm i && npm run webpack -- --mode=production
      working-directory: site
    - name: Publish
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_PAGES_EDIT_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: wgpu-game-of-life-fornwall-net
        directory: site/dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
